import type { Locale } from "@/lib/i18n";

/** Fill `{placeholders}` in a dictionary string. */
export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? `{${k}}`));
}

const it = {
  skip: "Vai al contenuto principale",
  nav: {
    label: "Navigazione principale",
    company: "Azienda",
    companyOverview: "Chi siamo",
    careers: "Lavora con noi",
    pressKit: "Kit stampa",
    solutions: "Soluzioni",
    solutionsOverview: "Panoramica ed ecosistema",
    services: "Servizi",
    projects: "Progetti",
    news: "News",
    compliance: "Compliance",
    certifications: "Certificazioni",
    legality: "Rating di legalità",
    privacy: "Privacy Policy",
    contact: "Contatti",
    menu: "Menu",
    close: "Chiudi",
    language: "Lingua",
    switchTo: "Passa alla versione italiana",
    allSolutions: "Tutte le soluzioni",
  },
  footer: {
    tagline: "Sistemi informativi per la prevenzione, la sanità territoriale e la Pubblica Amministrazione.",
    contacts: "Contatti",
    sections: "Sezioni",
    solutions: "Soluzioni",
    legal: "Informazioni legali",
    registered: "Sede legale",
    vat: "P. IVA",
    rights: "Tutti i diritti riservati.",
    backToTop: "Torna all’inizio",
  },
  common: {
    readMore: "Approfondisci",
    discover: "Scopri",
    back: "Indietro",
    contactUs: "Contattaci",
    wantToKnowMore: "Vuoi saperne di più?",
    wantToKnowMoreBody: "Raccontaci il tuo servizio: ti mostriamo come l’applicazione si adatta alla tua organizzazione.",
    breadcrumb: "Percorso",
    home: "Home",
    download: "Scarica",
    pdf: "PDF",
    source: "Fonte",
    published: "Pubblicato il",
    relatedSolutions: "Soluzioni collegate",
    relatedNews: "Articoli collegati",
    photo: "Foto",
    applications: "applicazioni",
    application: "applicazione",
    noPage: "Scheda in preparazione",
  },
  solution: {
    family: "Ambito",
    whoUses: "Chi la usa",
    features: "Funzionalità",
    norms: "Riferimenti normativi",
    integrations: "Integrazioni",
    also: "Nello stesso ambito",
    otherAreas: "Altri ambiti",
    context: "Contesto",
    index: "Indice della scheda",
  },
  ecosystem: {
    actors: "Persone e organizzazioni",
    platforms: "Piattaforme",
    all: "Tutti",
    selectHint: "Seleziona un gruppo",
    uses: "usa",
    usesPlural: "Piattaforme usate",
    listView: "Elenco testuale",
  },
  projects: {
    label: "Progetti",
    title: "Progetti sul territorio.",
    lede: "Casi documentati: dove le piattaforme Edinext sono al lavoro, con chi e con quali risultati. Ogni scheda si basa su fonti pubblicate.",
    client: "Ente",
    place: "Luogo",
    year: "Anno",
    context: "Contesto",
    solution: "Soluzione",
    actors: "Attori",
    outcome: "Risultato",
    sources: "Fonti",
  },
  news: {
    label: "News",
    title: "Notizie e comunicati.",
    lede: "Lo sviluppo delle applicazioni, la loro adozione sul territorio, le posizioni aperte.",
    all: "Tutte",
  },
  solutions: {
    label: "Soluzioni",
    title: "Un ecosistema di applicazioni per la sanità pubblica.",
    lede: "Le applicazioni Edinext sono modulari, flessibili e personalizzabili. Collegano chi eroga i servizi — ASL, strutture, Regioni — a chi li riceve: cittadini, imprese, scuole, associazioni.",
    mapTitle: "La mappa delle relazioni",
    mapLede: "Seleziona un gruppo di persone per vedere con quali piattaforme lavora e in che modo.",
    catalogueTitle: "Il catalogo, per ambito",
    reportTitle: "Report e analisi dei dati",
    reportBody:
      "Con le applicazioni Edinext è semplice analizzare i dati con report, griglie e grafici personalizzabili. Ricerca e modifica sono rapide e intuitive, e tutte le soluzioni si integrano con le applicazioni in dotazione alle ASL e alle strutture sanitarie.",
  },
  meta: {
    siteDescription:
      "Sistemi informativi per i Dipartimenti di Prevenzione delle ASL, le strutture sanitarie, sociosanitarie e sociali e le Regioni.",
    organizationDescription:
      "Sistemi informativi per il Dipartimento di Prevenzione delle ASL e per le strutture sanitarie, sociosanitarie e sociali, pubbliche e private.",
    newsTitle: "News e comunicati",
    solutionsTitle: "Soluzioni — Software per ASL e strutture sanitarie",
    solutionsDescription:
      "17 applicazioni per ASL, Regioni e strutture sanitarie: prevenzione, vaccinazioni, sanità territoriale, consultori, donazione del sangue.",
  },
  labels: {
    phone: "Telefono",
    newTab: "(si apre in una nuova scheda)",
    previous: "Precedente",
    next: "Successivo",
    areas: "ambiti",
    data: "Dati",
    atAGlance: "In sintesi",
    nextProject: "Progetto successivo",
    applyByEmail: "Invia la candidatura",
    regulatoryTimeline: "Cronologia normativa",
    applications: "Applicazioni",
    familyNormsTitle: "Le norme a cui rispondono.",
    catalogueLede:
      "{count} schede dettagliate. Ogni applicazione è indipendente e si integra con le altre e con i sistemi in uso negli enti.",
  },
  solutionPage: {
    inEcosystem: "Nell’ecosistema",
    ecosystemCaption: "Le linee evidenziano i gruppi di persone che lavorano con {name}.",
    ecosystemFigure: "{name} e i gruppi di persone che la usano, nella mappa delle piattaforme Edinext.",
    actors: "Attori",
    norms: "Norme",
    schema: "Schema",
    rolesTitle: "Persone diverse, un solo sistema.",
  },
  quality: {
    isoTitle: "Sistema di gestione per la qualità",
    reference: "Rif.",
    pdrTitle: "Politica per la parità di genere",
    pdrNote: "Inclusione e pari opportunità",
    legalityCode: "Rating di legalità",
    legalityTitle: "Attribuito dall’AGCM",
  },
  errorPage: {
    title: "Si è verificato un errore",
    body: "La pagina non è stata caricata correttamente. Riprova, oppure scrivici a info@edinext.it.",
    retry: "Riprova",
    home: "Torna alla home",
  },
  notFound: {
    title: "Pagina non trovata",
    body: "L’indirizzo potrebbe essere cambiato con il nuovo sito. Riparti dalla home o dal catalogo delle soluzioni.",
    home: "Torna alla home",
  },
};

export type UI = typeof it;

const en: UI = {
  skip: "Skip to main content",
  nav: {
    label: "Main navigation",
    company: "Company",
    companyOverview: "About us",
    careers: "Careers",
    pressKit: "Press kit",
    solutions: "Solutions",
    solutionsOverview: "Overview and ecosystem",
    services: "Services",
    projects: "Projects",
    news: "News",
    compliance: "Compliance",
    certifications: "Certifications",
    legality: "Legality rating",
    privacy: "Privacy Policy",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    language: "Language",
    switchTo: "Switch to the English version",
    allSolutions: "All solutions",
  },
  footer: {
    tagline: "Information systems for prevention, community healthcare and public administration.",
    contacts: "Contact",
    sections: "Sections",
    solutions: "Solutions",
    legal: "Legal information",
    registered: "Registered office",
    vat: "VAT no.",
    rights: "All rights reserved.",
    backToTop: "Back to top",
  },
  common: {
    readMore: "Read more",
    discover: "Discover",
    back: "Back",
    contactUs: "Contact us",
    wantToKnowMore: "Want to know more?",
    wantToKnowMoreBody: "Tell us about your service and we’ll show you how the application adapts to your organisation.",
    breadcrumb: "Breadcrumb",
    home: "Home",
    download: "Download",
    pdf: "PDF",
    source: "Source",
    published: "Published on",
    relatedSolutions: "Related solutions",
    relatedNews: "Related articles",
    photo: "Photo",
    applications: "applications",
    application: "application",
    noPage: "Page in preparation",
  },
  solution: {
    family: "Area",
    whoUses: "Who uses it",
    features: "Features",
    norms: "Regulatory references",
    integrations: "Integrations",
    also: "In the same area",
    otherAreas: "Other areas",
    context: "Context",
    index: "On this page",
  },
  ecosystem: {
    actors: "People and organisations",
    platforms: "Platforms",
    all: "All",
    selectHint: "Select a group",
    uses: "uses",
    usesPlural: "Platforms used",
    listView: "Text list",
  },
  projects: {
    label: "Projects",
    title: "Projects on the ground.",
    lede: "Documented cases: where Edinext platforms are at work, with whom and with what results. Every case is based on published sources.",
    client: "Organisation",
    place: "Place",
    year: "Year",
    context: "Context",
    solution: "Solution",
    actors: "Actors",
    outcome: "Outcome",
    sources: "Sources",
  },
  news: {
    label: "News",
    title: "News and announcements.",
    lede: "How our applications are developed and adopted across the territory, and our open positions.",
    all: "All",
  },
  solutions: {
    label: "Solutions",
    title: "An ecosystem of applications for public healthcare.",
    lede: "Edinext applications are modular, flexible and customisable. They connect those who provide services — health authorities, facilities, regions — with those who receive them: citizens, businesses, schools, associations.",
    mapTitle: "The relationship map",
    mapLede: "Select a group of people to see which platforms they work with, and how.",
    catalogueTitle: "The catalogue, by area",
    reportTitle: "Reporting and data analysis",
    reportBody:
      "Edinext applications make it easy to analyse data through customisable reports, grids and charts. Searching and editing are quick and intuitive, and every solution integrates with the applications already in use at health authorities and healthcare facilities.",
  },
  meta: {
    siteDescription:
      "Information systems for health authority Prevention Departments, healthcare and social-care facilities and regional governments.",
    organizationDescription:
      "Information systems for the Prevention Departments of Italian local health authorities and for public and private healthcare, social-care and social facilities.",
    newsTitle: "News and announcements",
    solutionsTitle: "Solutions — Software for health authorities and facilities",
    solutionsDescription:
      "17 applications for health authorities, regions and facilities: prevention, vaccination, community care, family health centres, blood donation.",
  },
  labels: {
    phone: "Phone",
    newTab: "(opens in a new tab)",
    previous: "Previous",
    next: "Next",
    areas: "areas",
    data: "Data",
    atAGlance: "At a glance",
    nextProject: "Next project",
    applyByEmail: "Apply by e-mail",
    regulatoryTimeline: "Regulatory timeline",
    applications: "Applications",
    familyNormsTitle: "The regulations they respond to.",
    catalogueLede:
      "{count} detailed product pages. Each application is independent and integrates with the others and with the systems already in use.",
  },
  solutionPage: {
    inEcosystem: "In the ecosystem",
    ecosystemCaption: "The highlighted lines show the groups of people who work with {name}.",
    ecosystemFigure: "{name} and the groups of people who use it, within the map of Edinext platforms.",
    actors: "Actors",
    norms: "Norms",
    schema: "Overview",
    rolesTitle: "Different people, one system.",
  },
  quality: {
    isoTitle: "Quality management system",
    reference: "Ref.",
    pdrTitle: "Gender equality policy",
    pdrNote: "Inclusion and equal opportunities",
    legalityCode: "Legality rating",
    legalityTitle: "Awarded by AGCM",
  },
  errorPage: {
    title: "Something went wrong",
    body: "The page did not load correctly. Please try again, or write to info@edinext.it.",
    retry: "Try again",
    home: "Back to home",
  },
  notFound: {
    title: "Page not found",
    body: "The address may have changed with the new website. Start again from the home page or the solutions catalogue.",
    home: "Back to home",
  },
};

export const ui: Record<Locale, UI> = { it, en };
